namespace PaketLoadScripts

#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.AspNetCore.Authentication.Core.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.AspNetCore.Http.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.AspNetCore.HttpOverrides.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.Options.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\System.Buffers.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\System.IO.Pipelines.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\System.Numerics.Vectors.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\System.Runtime.CompilerServices.Unsafe.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\System.Security.Principal.Windows.fsx" 
#r "C:\\Users\\Isaac\\.nuget\\packages\\microsoft.aspnetcore.server.iisintegration\\2.2.1\\lib\\netstandard2.0\\Microsoft.AspNetCore.Server.IISIntegration.dll" 