namespace PaketLoadScripts

#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.AspNetCore.Http.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.Configuration.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.Configuration.EnvironmentVariables.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.Configuration.FileExtensions.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.DependencyInjection.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.FileProviders.Physical.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.Hosting.Abstractions.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.Logging.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\Microsoft.Extensions.Options.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\System.Diagnostics.DiagnosticSource.fsx" 
#load "C:\\Users\\Isaac\\Source\\Repos\\paketbug\\.paket\\load\\System.Reflection.Metadata.fsx" 
#r "C:\\Users\\Isaac\\.nuget\\packages\\microsoft.aspnetcore.hosting\\2.2.7\\lib\\netstandard2.0\\Microsoft.AspNetCore.Hosting.dll" 